// Who We Are + About DevelMo content, ported + rewritten from the original site.

export type AboutContent = {
  heading: string;
  lead: string;
  vision: string;
  mission: string;
  story: string[];
  values: { title: string; body: string }[];
  differentiators: { title: string; body: string }[];
};

export const aboutContent: Record<string, AboutContent> = {
  "who-we-are": {
    heading: "Who We Are",
    lead: "DevelMo is a UK-registered AI, computer vision, cloud, and custom software company. We build practical systems that put modern technology to work inside real businesses, scaling teams through AI that fits the way they already operate. With offices in the United Kingdom, Australia, Saudi Arabia, and Pakistan, we deliver across more than 23 countries.",
    vision: "A world where advanced AI and computer vision are not reserved for a handful of technology giants, but are accessible, dependable, and shaped to fit the businesses that use them.",
    mission: "To scale businesses through AI that fits. We pair deep engineering in computer vision, machine learning, and cloud with a clear understanding of how each client actually works, so the technology we ship solves the problem in front of it rather than a generic one.",
    story: ["DevelMo began with a simple conviction: most companies do not need more technology, they need the right technology applied well. Too many AI projects stall because they are built in isolation from the business they are meant to serve. We set out to close that gap, combining genuine engineering depth with a habit of starting from the problem rather than the tool.", "From our base in London, we have grown into a company that works across the United Kingdom, Australia, Saudi Arabia, and Pakistan, serving clients in more than 23 countries. That spread is deliberate. It keeps us close to our customers across time zones and gives us a team drawn from different markets, disciplines, and ways of thinking.", "Today our work spans six areas: digital transformation, AI and data solutions, vision and automation, security and emerging technology, cloud and DevOps engineering, and tech talent and staff augmentation. We support organisations in healthcare, telecommunications, energy, travel, e-commerce, fintech, the public sector, retail, gaming, and the startup world.", "We also build our own products. CrowdIQ and PadelIQ are where we prove our methods on our own time and budget, before bringing the same standards to client work. They keep us honest about what good computer vision and AI engineering really take."],
    values: [{"title": "Fit Before Flash", "body": "We start with how a business actually runs and build technology around it. A model or a dashboard only matters if it earns its place in real operations, so we measure ourselves on the problem solved, not the buzzwords used."}, {"title": "Engineering Depth", "body": "Computer vision, machine learning, cloud, and software are crafts. We invest in getting the hard parts right, from data pipelines and MLOps to security and infrastructure, because shortcuts in the foundations always surface later."}, {"title": "Plain Speaking", "body": "We explain what we are building, what it will and will not do, and what it costs, in language anyone on the client side can follow. Clarity early prevents disappointment late."}, {"title": "Ownership", "body": "We treat every engagement as if the outcome were ours. That means following a problem through to a working result, not handing over a proof of concept and walking away."}, {"title": "Close Partnership", "body": "With teams across four countries and clients in more than 23, we stay close to the people we serve. Good systems come from understanding the day to day work they are meant to support."}, {"title": "Built to Last", "body": "We design for the long run, with secure, maintainable, well documented systems that a client can keep running and growing long after we have shipped them."}],
    differentiators: [{"title": "Specialists, Not Generalists", "body": "AI, computer vision, and cloud are our core, not a side line. Products like CrowdIQ and PadelIQ show we build and run real vision systems in production, not just slide decks about them."}, {"title": "One Team, Full Stack", "body": "From digital transformation and custom software to AI, data engineering, MLOps, and security, we cover the whole path from idea to deployed system. Clients get a single accountable partner rather than a chain of vendors."}, {"title": "Global Reach, Local Attention", "body": "Offices in the United Kingdom, Australia, Saudi Arabia, and Pakistan let us serve clients across more than 23 countries while staying close to each one, across time zones and markets."}, {"title": "Talent On Demand", "body": "Beyond delivery, we extend client teams with on demand developers, AI and ML specialists, and dedicated project squads, so organisations can scale capability up or down without losing momentum."}],
  },
  "about-develmo": {
    heading: "About DevelMo",
    lead: "DevelMo is a UK-registered AI technology company that builds intelligent, custom software and computer vision systems, alongside a growing line of ready-made products. We work on a simple principle: technology should fit your business, not the other way around. From offices across the United Kingdom, Australia, Saudi Arabia, and Pakistan, our teams deliver for clients in more than 23 countries.",
    vision: "We envision a future where intelligent technology molds itself around the way businesses actually work, making innovation more human, more seamless, and more powerful.",
    mission: "We create intelligent, custom-built AI and software that empower teams to solve real problems, drive efficiency, and grow with confidence.",
    story: ["DevelMo began with a conviction that most software asks businesses to adapt to the tool, when it should be the other way around. Too many teams were paying for template platforms that almost fit, then bending their workflows to match. We set out to build the opposite: AI and software shaped around how an organisation actually operates, from the first conversation to the system in production.", "That conviction has grown into a company that spans custom engineering and finished products. On the services side we cover the full stack of modern technology work, from web and mobile development and UI/UX design through to predictive analytics, generative AI and LLM integration, computer vision, cloud and DevOps engineering, and AI-driven cybersecurity. On the product side we ship tools that put those same capabilities directly into customers' hands.", "Our computer vision and analytics work is best seen in our own products. CrowdIQ turns ordinary camera footage into retail intelligence, measuring foot traffic, customer demographics, and dwell time, then packaging it into reports teams can act on. PadelIQ extends that vision expertise into a new domain, proving the same engineering can move from the shop floor to the sports court.", "Today DevelMo operates as one team across four countries, registered in the United Kingdom and serving clients in more than 23. Whether a client needs a dedicated project team, a single AI specialist, or a finished product, the goal stays the same: technology that fits the business and earns its place in daily use."],
    values: [{"title": "Fit before features", "body": "We start with how your business actually works, then build to match it. Custom solutions beat templates because they remove friction instead of adding it, and that is where real efficiency comes from."}, {"title": "Intelligence with a purpose", "body": "AI is a means, not a headline. We apply predictive analytics, generative AI, and computer vision to solve concrete problems, and we are honest about where they help and where they do not."}, {"title": "Engineering you can trust", "body": "From cloud infrastructure and CI/CD to MLOps and AI-driven security, we build systems meant to run in production, stay maintainable, and hold up under real load."}, {"title": "One global team", "body": "Our people in the United Kingdom, Australia, Saudi Arabia, and Pakistan work as a single unit. Clients in more than 23 countries get the same standard of delivery wherever they are based."}, {"title": "Clarity over jargon", "body": "We explain what we are building in plain language, set realistic expectations, and let working software do the talking. No mystery, no buzzword soup."}, {"title": "Built to grow with you", "body": "We design for what comes next, so the system that fits today still fits as your team, your data, and your ambitions scale."}],
    differentiators: [{"title": "Custom builds and proven products under one roof", "body": "Few companies offer both bespoke AI engineering and shipped products. Our work on CrowdIQ and PadelIQ means the same teams who build for clients have already solved hard problems in production, and that experience flows back into every project."}, {"title": "Deep computer vision capability", "body": "Vision is a core strength, not a side service. We deliver facial recognition, image generation, and workflow automation, and our products turn raw camera footage into measurable business intelligence."}, {"title": "Full-stack delivery, from idea to MLOps", "body": "We cover the whole lifecycle: digital transformation, AI and data solutions, cloud and DevOps, security, and emerging tech such as blockchain, digital twins, and IoT. One partner can take a concept all the way to a maintained, monitored system."}, {"title": "A genuinely global footprint", "body": "With offices across four countries and clients in more than 23, we combine local presence with the reach to support organisations wherever they operate, backed by a UK registration."}],
  },
};
