// Mirrors develmo.com /who-we-help: 10 industries. Content ported + rewritten from the original site.

export type Industry = {
  slug: string;
  name: string;
  icon: string;
  blurb: string;
  challenge: string;
  approach?: string;
  solutions: string[];
  outcomes?: { title: string; body: string }[];
  faqs?: { q: string; a: string }[];
};

export const industries: Industry[] = [
  {
    slug: "healthcare-pharmaceuticals",
    name: "Healthcare & Pharmaceuticals",
    icon: "healthcare",
    blurb: "Custom software, AI and computer vision for hospitals, pharma and health-tech, built compliant from day one.",
    challenge: "Patient data sits trapped in disconnected systems while clinical and back-office work stays manual, slowing care and inflating cost. Every new tool has to clear HIPAA, GDPR and HL7 before it can touch a single record.",
    approach: "We build healthcare and pharma software the way the sector actually demands it: secure, interoperable and audit-ready from the first commit, not bolted on later. Our teams ship custom EHR and telehealth platforms, pharma CRM and ERP, and AI models for triage, imaging and analytics, designed around HL7/FHIR data flows and real clinical workflows. You get a partner that understands the regulatory ground rules, so the technology earns trust instead of creating risk.",
    solutions: ["Custom EHR/EMR systems with centralised, secure patient records", "Telehealth and virtual-care platforms for connected remote treatment", "Pharma CRM and ERP to streamline sales, supply and operations", "Patient portals and mobile apps for self-service and engagement", "Clinical Trial Management Systems (CTMS) for research workflows", "AI triage, medical imaging and analytics dashboards for real-time decisions"],
    outcomes: [{"title": "Compliance built in, not bolted on", "body": "Platforms architected around HIPAA, GDPR and HL7/FHIR from day one, so audits, data residency and consent are handled by design rather than retrofitted under pressure."}, {"title": "One source of truth for patient data", "body": "Siloed records, scheduling and claims are unified into interoperable systems, cutting duplicate entry and giving clinicians and operators a single, accurate view."}, {"title": "Decisions backed by real-time intelligence", "body": "AI triage, imaging models and analytics dashboards surface insight at the point of care and across operations, turning raw clinical and trial data into faster, safer decisions."}],
    faqs: [{"q": "Can you build software that meets HIPAA, GDPR and HL7 requirements?", "a": "Yes. Compliance is a design constraint we work to from the start, not an afterthought. We architect access control, encryption, audit logging and consent into the system and align data exchange with HL7/FHIR so your platform is regulation-ready when it ships."}, {"q": "Do you integrate with our existing EHR and hospital systems?", "a": "We do. Most of our work connects to systems already in place rather than replacing everything. Using HL7/FHIR and standard APIs, we link EHR/EMR, lab, scheduling and pharma platforms so data moves cleanly across your stack."}, {"q": "Where does AI and computer vision fit in healthcare and pharma?", "a": "We apply it where it is defensible and useful: triage and clinical decision support, medical image analysis, document and claims automation, and analytics across operations and clinical trials. Models are validated against your data and kept under human oversight for clinical decisions."}],
  },
  {
    slug: "telecommunication",
    name: "Telecommunication",
    icon: "telecom",
    blurb: "Custom software and AI that keep networks, billing and customer operations fast, observable and ready for 5G.",
    challenge: "Telecom runs on sprawling networks, legacy OSS/BSS and rising subscriber expectations, where every minute of downtime and every blind spot in the data costs revenue. 5G, IoT and cloud raise the ceiling on what is possible and the bar on what operators must support.",
    approach: "We build telecom systems that hold up under real load: network management and analytics platforms, modern subscriber and billing tooling, and self-service portals that take pressure off support. Everything is engineered for uptime and throughput, integrated cleanly into your existing OSS/BSS and cloud stack rather than bolted on, and instrumented so you can see what the network and the customer are actually doing. We add AI where it earns its place, from churn prediction to anomaly detection, not as a label on the box.",
    solutions: ["Network management and monitoring platforms with real-time observability and anomaly detection", "Churn prediction and retention models built on your subscriber and usage data", "Modern billing and subscriber-management systems that scale with the base", "Customer portals and self-service apps that cut support volume", "OSS/BSS integration that connects legacy systems to new cloud services", "Telecom analytics dashboards and field-service apps for technicians in the field"],
    outcomes: [{"title": "Less downtime, faster response", "body": "Real-time monitoring and anomaly detection surface network issues before subscribers feel them, so teams act on signal instead of trouble tickets."}, {"title": "Lower cost to serve", "body": "Self-service portals and automated workflows shift routine requests away from agents, freeing support to handle what actually needs a human."}, {"title": "Decisions backed by your own data", "body": "Unified analytics turn fragmented network, billing and usage data into churn signals and operational insight you can act on, not just report on."}],
    faqs: [{"q": "Can you integrate with our existing OSS/BSS and legacy systems?", "a": "Yes. Most of our telecom work is integration, not greenfield. We connect new services, portals and analytics to the OSS/BSS, billing and provisioning systems you already run, and migrate incrementally so there is no big-bang cutover."}, {"q": "Are you building generic dashboards or models trained on our data?", "a": "On your data. Churn, anomaly detection and forecasting are only useful when they learn your network and your subscriber behaviour, so we train and tune against your sources rather than shipping a one-size template."}, {"q": "Is your software ready for 5G and IoT scale?", "a": "We architect for it from the start. Systems are designed to handle the device counts, data volumes and throughput that 5G and IoT bring, with cloud-native deployment and DevOps practices so capacity scales with demand."}],
  },
  {
    slug: "oil-gas-and-energy",
    name: "Oil, Gas & Energy",
    icon: "oilgas",
    blurb: "Custom software, computer vision, and cloud platforms that turn field operations, assets, and safety data into decisions energy teams can act on in real time.",
    challenge: "Energy operations run on ageing systems, paper inspections, and data trapped across rigs, control rooms, and back offices, so downtime, safety risk, and slow decisions become the norm. Teams need to digitalise without ripping out the infrastructure they depend on every day.",
    approach: "We build software around how energy teams actually work, from offshore rigs and remote sites to the control room. That means offline-first mobile apps for technicians, cloud dashboards for decision-makers, and computer vision and predictive analytics that surface problems before they cost you. Everything is designed to layer onto existing operations rather than disrupt them.",
    solutions: ["Asset tracking and live performance monitoring across sites, with a single source of truth for equipment health", "Predictive maintenance using sensor and historical data to flag failures before they cause unplanned downtime", "Real-time data visualisation and reporting that pulls field and SCADA data into cloud dashboards", "Computer-vision inspection and safety monitoring: automated defect detection, PPE and zone compliance, and visual audit trails", "Offline-first mobile apps for digital inspections and field workflows that sync when connectivity returns", "Workflow automation across field and back-office to cut paperwork and manual handoffs"],
    outcomes: [{"title": "Less unplanned downtime", "body": "Predictive maintenance and live asset monitoring catch degradation early, so crews intervene on schedule instead of reacting to failures."}, {"title": "Faster, safer audits", "body": "Digital inspections and computer-vision compliance checks replace paper trails with searchable, timestamped, defensible records."}, {"title": "Decisions on real data", "body": "Field and sensor data flows into one cloud view, giving operators and managers the same accurate picture in real time."}],
    faqs: [{"q": "Can your software work on offshore rigs and remote sites with poor connectivity?", "a": "Yes. We build offline-first mobile apps that let technicians capture inspections and field data with no connection, then sync automatically to the cloud once a link is available. Critical workflows never depend on live connectivity."}, {"q": "Do we have to replace our existing systems to work with you?", "a": "No. We design solutions to integrate with the SCADA, sensor, and back-office systems you already run, layering modern dashboards, automation, and analytics on top rather than forcing a rip-and-replace."}, {"q": "How does computer vision fit into oil, gas, and energy operations?", "a": "We apply computer vision to automate visual inspections, detect equipment defects and corrosion, and monitor safety compliance such as PPE use and restricted-zone access, turning camera and drone footage into auditable, actionable data."}],
  },
  {
    slug: "travel-hospitality",
    name: "Travel & Hospitality",
    icon: "hospitality",
    blurb: "Software and AI that lift guest experience and tighten operations across every property and channel.",
    challenge: "Travel demand swings hard by season, event and weather while guest expectations keep climbing, and most operators run on disconnected booking, property and loyalty systems that cannot see the full picture. The result is missed revenue at peak, idle capacity off-peak, and a guest journey that breaks every time data fails to follow the traveller.",
    approach: "We build the connective tissue: cloud-native booking, property and guest platforms that share one source of truth and integrate cleanly with the OTAs, payment gateways and PMS you already run. On top of that data we layer practical AI such as demand forecasting, dynamic pricing signals and guest-experience analytics, plus computer vision for footfall, queues and on-site flow. Everything is mobile-first, multi-property and built to launch across markets with native language and currency support.",
    solutions: ["Mobile-first booking engines that drive direct reservations and cut OTA commission", "Guest-experience apps spanning check-in, concierge, in-stay requests and checkout", "Property and operations platforms unifying room inventory, housekeeping and staffing", "Demand forecasting and dynamic pricing signals tuned to season, event and channel", "CRM and loyalty systems with personalised offers that bring guests back", "Integrations across OTAs, payment gateways and property management systems via clean APIs"],
    outcomes: [{"title": "More direct, higher-value bookings", "body": "A fast, mobile-first booking experience and loyalty mechanics shift volume away from high-commission OTAs and lift the value of each reservation."}, {"title": "Capacity matched to real demand", "body": "Forecasting and dynamic pricing signals help fill rooms and seats at peak and protect margin off-peak, instead of reacting after the fact."}, {"title": "One connected guest journey", "body": "Booking, property, loyalty and on-site data share a single source of truth, so the experience holds together from first search to repeat stay."}],
    faqs: [{"q": "Can you work with our existing PMS, booking engine and OTA channels?", "a": "Yes. We integrate through clean, documented APIs rather than ripping out what works, connecting your property management system, payment gateways and OTA channels so data flows in one direction of truth. Where a system has no usable API, we build the connector."}, {"q": "Will this scale from a single property to a multi-market group?", "a": "It is built to. The platforms are cloud-native and multi-property from day one, with native language and currency support, so you can add sites, features and new markets without rebuilding the core."}, {"q": "Where does AI actually pay off in travel and hospitality?", "a": "The reliable wins are demand forecasting and dynamic pricing, personalised loyalty and offers, and computer vision for footfall, queues and on-site flow. We start where the data already supports a measurable result and expand from there, rather than bolting on AI for its own sake."}],
  },
  {
    slug: "e-commerce",
    name: "E-commerce",
    icon: "ecommerce",
    blurb: "Custom commerce platforms with AI search, recommendations and forecasting built in, so you convert more and scale without re-platforming.",
    challenge: "Shoppers abandon when they cannot find the right product, and margins erode when stock and pricing decisions are made on guesswork. Most stores bolt on generic plugins that buckle at peak traffic and never learn from buyer behaviour.",
    approach: "We build headless, API-first commerce on a foundation that holds up under load, then layer in the intelligence that actually moves revenue: visual and semantic search, real-time personalisation, and demand forecasting trained on your own data. Whether you are launching net-new or migrating off Shopify, Magento or WooCommerce, we ship in stages so the storefront keeps selling throughout. The result is a system that converts better today and keeps getting smarter as it learns.",
    solutions: ["Custom and headless commerce builds with an API-driven, mobile-first storefront", "Visual and semantic product search so shoppers find items by image or intent, not exact keywords", "Personalised recommendations and merchandising that adapt in real time to each session", "Demand and inventory forecasting to cut stockouts, overstock and markdown waste", "Zero-downtime migration from Shopify, Magento or WooCommerce, plus payment, shipping, CRM and ERP integration", "Performance optimisation and ongoing engineering support to keep checkout fast at peak traffic"],
    outcomes: [{"title": "Higher conversion", "body": "AI-driven search and personalisation surface the right product faster, turning more sessions into checkouts and lifting average order value."}, {"title": "Leaner inventory", "body": "Forecasting grounded in your own sales data reduces stockouts and overstock, freeing working capital and cutting markdown losses."}, {"title": "Scales at peak", "body": "Headless architecture and tuned infrastructure hold up through launches and sale events without the slowdowns that kill carts."}],
    faqs: [{"q": "Can you migrate our existing store without taking it offline?", "a": "Yes. We migrate from Shopify, Magento, WooCommerce and custom stacks in staged cutovers, validating data, URLs and integrations as we go so the storefront keeps selling and SEO holds throughout."}, {"q": "Do we have to replace our whole platform to add AI?", "a": "No. Visual search, recommendations and forecasting are delivered as APIs that plug into your current storefront. We start where the return is clearest and expand from there, no rip-and-replace required."}, {"q": "How do recommendations and search improve over time?", "a": "They learn from your real traffic and sales. Models retrain on session, catalogue and order data, so relevance and forecast accuracy keep improving as you grow rather than staying static like a generic plugin."}],
  },
  {
    slug: "banking-and-fintech",
    name: "Banking & Fintech",
    icon: "banking",
    blurb: "Ship banking and fintech products that feel simple, clear fraud and compliance in real time, and scale without breaking trust.",
    challenge: "Banks are weighed down by legacy cores while fintechs race to launch, and both pay for it in slow manual review, fraud losses, and compliance overhead. Every new feature has to clear a high bar for security and regulation before it ever reaches a customer.",
    approach: "We build payment, wallet, and digital-banking products on modern APIs that sit cleanly on top of your core, so you ship faster without ripping out what works. AI handles the heavy, repetitive work: scoring transactions for fraud, reading KYC documents, and flagging anomalies, while keeping a human in the loop where it counts. Security and compliance are designed in from the first commit, not bolted on before launch.",
    solutions: ["Real-time fraud and anomaly detection that scores transactions as they happen and routes only genuine risk to human review", "Automated KYC and onboarding: document capture, ID verification, and data extraction that cut sign-up from days to minutes", "Core banking integration through modern APIs, connecting legacy systems to new digital products without a full rip-and-replace", "Custom digital wallets, payment platforms, and mobile and web apps built for scale and a clean customer experience", "Security-first engineering: encryption in transit and at rest, audit trails, and compliance with PCI DSS and GDPR built in", "Cloud infrastructure and DevOps that keep regulated workloads reliable, observable, and ready to scale globally"],
    outcomes: [{"title": "Less fraud, fewer false alarms", "body": "Machine-learning models catch fraudulent and anomalous activity in real time while suppressing false positives, so analysts spend their time on the cases that actually matter instead of clearing noise."}, {"title": "Onboarding measured in minutes", "body": "Automated identity verification and document handling remove the manual back-and-forth from KYC, letting customers open accounts faster and your team handle far higher volume without adding headcount."}, {"title": "Audit-ready by design", "body": "Encryption, access controls, and complete audit trails are part of the build from day one, so PCI DSS and GDPR reviews become a confirmation rather than a scramble."}],
    faqs: [{"q": "Can you integrate with our existing core banking system?", "a": "Yes. We connect to legacy cores and third-party systems through modern APIs and an integration layer, so you can launch new digital products incrementally instead of attempting a single high-risk replacement."}, {"q": "How do you handle security and regulatory compliance?", "a": "Security is designed in from the start, not added before launch. We encrypt data in transit and at rest, enforce access controls and audit logging, and build to standards including PCI DSS and GDPR, with rigorous testing throughout."}, {"q": "Do you build full platforms or just specific AI features?", "a": "Both. We can ship a focused MVP or a single capability such as fraud scoring or KYC automation, and we also build and scale full payment and digital-banking platforms for global use."}],
  },
  {
    slug: "public-sector",
    name: "Public Sector",
    icon: "public",
    blurb: "Secure, privacy-aware software and AI that make public services faster to use and easier to run.",
    challenge: "Public bodies run on ageing systems and disconnected data, so citizens wait and staff drown in manual casework. Every modernisation also has to clear a higher bar on security, privacy and public trust.",
    approach: "We build government software the way it should work: clear citizen portals, connected case and licensing systems, and live dashboards, layered with AI only where it earns its place. Data security and privacy are designed in from the first line of code, not bolted on, and everything is built to integrate with the legacy systems you already depend on. You get a transparent, collaborative build and long-term support rather than a vendor you have to chase.",
    solutions: ["Citizen portals for applications, payments and self-service access to services", "Permit, licensing and case-management platforms that replace paper and spreadsheets", "Real-time data dashboards and reporting for operational and public transparency", "Compliance and audit tooling built to meet strict regulatory and records requirements", "Privacy-aware analytics and document automation that keep sensitive data protected", "AI-powered cybersecurity and threat monitoring for public infrastructure"],
    outcomes: [{"title": "Shorter queues for citizens", "body": "Online portals and automated workflows replace forms, phone calls and counter visits, so routine requests are handled in minutes instead of weeks."}, {"title": "Less manual casework for staff", "body": "Connected case, permit and document systems remove duplicate data entry and chasing, freeing teams to focus on the decisions that actually need a person."}, {"title": "Security and compliance you can evidence", "body": "Privacy-by-design, full audit trails and AI-assisted monitoring make it straightforward to prove who did what, protect sensitive data and pass inspection."}],
    faqs: [{"q": "Can you work with our existing legacy systems?", "a": "Yes. Most of our public-sector work involves integrating with systems already in place rather than ripping them out. We build connectors and migration paths so new portals and tools sit on top of what you have, and modernise it in stages instead of one risky switchover."}, {"q": "How do you handle data security and privacy?", "a": "Security and privacy are designed in from the start, not added later. We apply privacy-by-design, least-privilege access, encryption and full audit logging, and we keep sensitive data within the controls your regulations require, including options for data to stay in your own cloud or on-premise environment."}, {"q": "Where does AI actually fit in public services?", "a": "Only where it makes a measurable difference and can be trusted. Typical uses are document and casework automation, privacy-aware analytics, and threat monitoring for cybersecurity. Anything affecting a citizen-facing decision stays explainable and keeps a person in the loop."}],
  },
  {
    slug: "retail-cpg",
    name: "Retail & CPG",
    icon: "retail",
    blurb: "Computer vision, demand intelligence and custom retail software that connect the shelf, the store and the screen.",
    challenge: "Retail and CPG brands run on systems that cannot see what is actually happening in store, so stockouts, missed footfall and guesswork pricing quietly erode margin. The data exists across POS, ecommerce and supply chain, but it stays siloed and arrives too late to act on.",
    approach: "We build retail software that turns physical and digital signals into decisions you can take today. Our CrowdIQ computer vision platform measures real in-store behaviour, while custom forecasting, integration and analytics work close the loop between the shelf and the back office. Every build is scoped for measurable ROI, not feature count, with our team hands-on from architecture through deployment.",
    solutions: ["CrowdIQ in-store computer vision: anonymised footfall, dwell time, queue length and zone heatmaps from your existing cameras", "AI demand forecasting that ties POS history, promotions and seasonality to per-SKU, per-location replenishment", "Inventory and supply-chain platforms with real-time stock visibility, supplier sync and fulfilment automation", "Unified commerce integrations that keep online, POS and in-store inventory in one source of truth", "Retail analytics dashboards correlating sales, foot traffic and conversion so merchandising and staffing decisions are evidence-led", "Custom POS, loyalty and branded mobile apps engineered to scale across store formats and regions"],
    outcomes: [{"title": "See the store, not just the till", "body": "Vision analytics expose what receipts never capture: where shoppers go, where they wait and where they leave. Layout, staffing and display decisions move from opinion to measured cause and effect."}, {"title": "Fewer stockouts, leaner inventory", "body": "Forecasting tuned to your own sales, promotions and seasonality keeps fast movers on the shelf and capital out of dead stock, with replenishment recommendations down to SKU and location."}, {"title": "One view across every channel", "body": "Connected POS, ecommerce and supply-chain data give merchandising, operations and finance a single, current picture, so teams act on the same numbers instead of reconciling spreadsheets."}],
    faqs: [{"q": "Do we need to install new cameras for CrowdIQ?", "a": "Usually not. CrowdIQ is designed to run on the IP cameras most stores already have, processing footage into anonymised behaviour metrics rather than identifying individuals, so you get analytics without a hardware overhaul."}, {"q": "Will this integrate with our existing POS, ERP and ecommerce stack?", "a": "Yes. We build around the systems you already run, integrating via their APIs to keep stock, sales and customer data in sync rather than forcing a rip-and-replace migration."}, {"q": "Is the in-store vision analytics privacy-compliant?", "a": "It is built privacy-first. Footage is converted into aggregate counts and movement patterns, with no facial recognition or personal identification, so you can measure behaviour while staying within GDPR and local regulations."}],
  },
  {
    slug: "startups",
    name: "Startups",
    icon: "startups",
    blurb: "Ship a real MVP or AI feature in weeks, built by a senior team that works like it is your own.",
    challenge: "Most startups have more roadmap than runway: not enough senior engineers, not enough time, and one shot to prove the product before the money or the market moves. Hiring is slow, agencies over-build, and an AI idea on a slide is a long way from something that holds up in production.",
    approach: "We embed a senior, full-stack team that plugs into your founders and ships like an in-house crew, minus the hiring lag and the lock-in. We build the minimum lovable product first, real software in front of real users, then layer in AI, computer vision, and cloud infrastructure only where it earns its place. Scale the team up to hit a launch or down to conserve cash, on a month-to-month basis, with no long contracts.",
    solutions: ["MVP and full-product builds in web and mobile, from discovery and prototype to launch and post-launch support", "Embedded AI and computer-vision features, from a working proof of concept to a model running in production", "Cloud-native architecture that is cheap to run early and scales when traction arrives", "Fractional senior team: add a designer, engineer, or product lead and scale up or down as the roadmap demands", "Investor-ready engineering: clean architecture, sane data, and a demo that survives the live walkthrough", "Plain-spoken technical guidance and a build-vs-buy view, so you do not pay to build what you do not need"],
    outcomes: [{"title": "Live in weeks, not quarters", "body": "A focused MVP scope and a senior team that already knows the stack means you get a working product in front of users fast, while the runway still matters."}, {"title": "AI that actually ships", "body": "We take an idea from proof of concept to a model serving real traffic, with the data pipeline, evaluation, and cloud infrastructure behind it, not a demo that dies after the pitch."}, {"title": "Spend that tracks traction", "body": "Build only what the product needs, run on infrastructure sized to current load, and flex team size month to month, so engineering cost moves with the business instead of ahead of it."}],
    faqs: [{"q": "Can you build the whole MVP, or just the AI part?", "a": "Either. We can own the full product end to end, web, mobile, backend, and cloud, or drop a senior engineer or computer-vision specialist into your existing team to build a specific feature. Most early-stage founders start with a full build and keep us on as a fractional team afterwards."}, {"q": "How fast can we launch?", "a": "It depends on scope, but a focused MVP is typically a matter of weeks rather than months, because we keep the first release deliberately small and resist over-engineering. We agree the minimum lovable scope up front so you launch, learn, and iterate without burning the round."}, {"q": "We are pre-funding and watching every dollar. Does this work for us?", "a": "Yes. There are no long-term contracts, you can scale the team up for a push and back down to conserve cash, and we will tell you honestly when an off-the-shelf tool beats a custom build. The goal is a product that proves itself to users and investors, not a bigger invoice."}],
  },
  {
    slug: "gaming",
    name: "Gaming",
    icon: "gaming",
    blurb: "Backends, live-ops tooling and player intelligence built for studios that ship at the pace of the gaming world.",
    challenge: "Studios have to hold up live multiplayer, ship content on a relentless cadence and keep play fair, all while player behaviour and load shift hour to hour. The hard part is doing it at scale without the backend, tooling or insight to see what is actually happening.",
    approach: "We build the systems behind the game, not just the game: scalable multiplayer and live-service backends, internal tools and live-ops dashboards your team actually uses, and analytics that turn raw telemetry into decisions. We work across Unity, Unreal, custom engines and cloud backends, and we plug AI and computer vision in where they earn their place, from matchmaking to anti-cheat. The result is a long-term engineering partner who works to your release cycle, not against it.",
    solutions: ["Scalable multiplayer and live-service backends built to hold up under real concurrency", "Live-ops dashboards for real-time control of events, economies and content", "Player and behaviour analytics that turn telemetry into retention and monetisation decisions", "AI-driven matchmaking and anti-cheat to keep sessions balanced and fair", "Custom dev tools, editors and automation that speed up your content pipeline", "Cross-platform web portals, companion apps and DevOps for smooth, frequent releases"],
    outcomes: [{"title": "Live services that stay up", "body": "Backends and DevOps designed for spikes and concurrency, so launches, events and live ops hold steady instead of buckling when players show up."}, {"title": "Decisions backed by player data", "body": "Telemetry and analytics surfaced in dashboards your team reads daily, so retention, balance and monetisation calls rest on evidence rather than guesswork."}, {"title": "More time on the game", "body": "Custom tools, editors and automation take the manual grind out of your content pipeline, freeing your developers to build the game instead of the plumbing."}],
    faqs: [{"q": "Which engines and platforms do you work with?", "a": "Unity, Unreal and custom engines, with cloud-native backends behind them. We build cross-platform across mobile, web and desktop, plus the companion apps, web portals and DevOps that keep releases moving."}, {"q": "Can you join an existing project mid-development?", "a": "Yes. We work to your release cycle and codebase, whether that means owning a backend or live-ops system end to end or embedding senior engineers alongside your team for a defined stretch."}, {"q": "Where does AI and computer vision actually fit in a game?", "a": "Where it pays off, not as a gimmick. Practical examples include matchmaking that balances sessions, behaviour analytics that flag churn and anti-cheat and anti-fraud that keep play fair. We scope it to a concrete outcome before building."}],
  },
];

export function getIndustry(slug: string) {
  return industries.find((i) => i.slug === slug);
}
