import type { Metadata } from "next";

// Per-page metadata helper: drives canonical + Open Graph + Twitter from the
// page's own title/description so shared links no longer all preview as the
// homepage. metadataBase (set in layout) resolves these relative URLs.
// Artwork is generated by `npm run og` (scripts/generate-og.mjs): full-bleed
// 1200x630 with everything inside the centred 600px "safe square", so clients
// that render the preview as a square tile (WhatsApp, iMessage, compact Slack)
// centre-crop it to fill without cutting content or leaving letterbox bars.
// Bump ?v= whenever the artwork changes — WhatsApp/Facebook cache OG images by
// full URL and will otherwise keep serving the old thumbnail for weeks.
export const OG_IMAGE = {
  url: "/og.jpg?v=2",
  width: 1200,
  height: 630,
  alt: "DevelMo, AI that fits your business",
};

export function pageMeta(opts: {
  title: string;
  description: string;
  path: string;
}): Metadata {
  const ogTitle = `${opts.title} | DevelMo`;
  return {
    title: opts.title,
    description: opts.description,
    alternates: { canonical: opts.path },
    openGraph: {
      type: "website",
      siteName: "DevelMo",
      url: opts.path,
      title: ogTitle,
      description: opts.description,
      images: [OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title: ogTitle,
      description: opts.description,
      images: [OG_IMAGE.url],
    },
  };
}
